# Generated by Django 2.2.3 on 2019-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolver',
            name='horas_devolveu',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='horas_pegou',
            field=models.TimeField(),
        ),
    ]
